#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt-get -y update
sudo apt-get -y install nginx
echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx without using systemctl
sudo /etc/init.d/nginx restart
