#!/usr/bin/env bash
# sets the port 80, and nginx must be running

rm -rf /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
