#!/usr/bin/env bash
# This is a script that gets Apache to run on the container and to return a page containing Hello Holberton when querying the root of it

apt-get update
apt-get -y install apache2
service apache2 restart
